name: Unity

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  IL2CPP_ADDITIONAL_ARGS: '--compiler-flags="-D_FORTIFY_SOURCE=2 -flto -O2 -fstack-protector-strong" --linker-flags="-flto -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" --verbose'

jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:${{ matrix.version }}-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2020.1.6f1
        target:
          - linux-il2cpp
          - windows
    steps:
      - name: Update git and xvfb
        run: |
          apt-get -y update
          apt-get -y install software-properties-common
          add-apt-repository ppa:git-core/ppa
          add-apt-repository ppa:rmescandon/yq
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install git xvfb curl yq moreutils

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.target }}
          restore-keys: |
            Library-

      - name: License
        run: echo "$UNITY_LICENSE" | tr -d '\r' > license.ulf

      - name: Activation
        run: xvfb-run --auto-servernum --server-args="-screen 0 640x480x24"
          /opt/Unity/Editor/Unity
          -batchmode
          -nographics
          -logFile /dev/stderr
          -quit
          -manualLicenseFile license.ulf
          || true

      - name: Build dir
        run: mkdir -p build

      - name: Use mono in windows
        working-directory: ProjectSettings
        run:
          yq ".PlayerSettings.scriptingBackend.Standalone = 0" ProjectSettings.asset |
          sponge ProjectSettings.asset
        if: matrix.target == 'windows'

      - name: Build
        working-directory: build
        shell: bash
        run: source ../target_data.sh ${{ matrix.target }} &&
          xvfb-run --auto-servernum --server-args="-screen 0 640x480x24"
          /opt/Unity/Editor/Unity
          -batchmode
          -nographics
          -quit
          -buildTarget $build_target
          -projectPath "../"
          $build_option "$build_path"
          -logFile /dev/stderr

      - name: Remove debug things
        working-directory: build
        run: rm -rf
          *_BackUpThisFolder_ButDontShipItWithYourGame
          *.debug

      - uses: actions/upload-artifact@v2
        if: matrix.target != 'linux-il2cpp'
        with:
          name: Build-${{ matrix.target }}
          path: build

      - name: Make tarball
        if: matrix.target == 'linux-il2cpp'
        run: |
          mv build game
          tar czvf game.tar.gz game

      - uses: actions/upload-artifact@v2
        if: matrix.target == 'linux-il2cpp'
        with:
          name: Build-${{ matrix.target }}
          path: game.tar.gz

  build2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2020.1.6f1
        target:
          - WebGL
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.target }}
          restore-keys: |
            Library-

      - name: yq
        run: |
          apt-get -y update
          apt-get -y install software-properties-common
          add-apt-repository ppa:rmescandon/yq
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install yq moreutils

      - name: Deactivate compression on WebGl
        working-directory: ProjectSettings
        run:
          yq '.PlayerSettings.webGLCompressionFormat = 2' ProjectSettings.asset |
          sponge ProjectSettings.asset

      - name: Build project
        uses: webbertakken/unity-builder@v1.2
        with:
          allowDirtyBuild: true
          unityVersion: ${{ matrix.version }}
          targetPlatform: ${{ matrix.target }}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.target }}
          path: build
